<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_GoogleReviews
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */

/**  @var $block Dss\GoogleReviews\Block\Badge */
?>
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>

<?php if ($block->getLanguage()): ?>
    <script>
        window.___gcfg = {
            lang: "<?= /* @noEscape */ $block->getLanguage() ?>"
        };
    </script>
<?php endif; ?>

<script>
    window.renderBadge = function () {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function () {
            window.gapi.ratingbadge.render(
                ratingBadgeContainer, {
                    "merchant_id": <?= /* @noEscape */ $block->getMerchantId() ?>,
                    "position": "<?= /* @noEscape */ $block->getPosition() ?>"
                });
    });
    }
</script>